services:
  - type: web
    name: gestion-stock-api
    env: php
    region: frankfurt
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://gestion-stock-api.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: gestion-stock-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gestion-stock-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: gestion-stock-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: gestion-stock-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gestion-stock-db
          property: password
databases:
  - name: gestion-stock-db
    plan: free
    region: frankfurt
    databaseName: gestionstock
    user: gestionuser
